"""Leakage-safe aggregates and horizon-specific features for offline training."""

from tramflow_ml.features.aggregate import AggregateIndex, aggregate
from tramflow_ml.features.build import (
    ENTITY_CAPACITY,
    HORIZON_INDEX,
    FeatureRequest,
    build_features,
    feature_names,
)
from tramflow_ml.features.calendar_features import calendar_feature_names, calendar_features
from tramflow_ml.features.coverage import CoverageCalendar, CoverageView
from tramflow_ml.features.events import (
    entity_keys,
    load_entity_keys,
    load_observations,
    observation_from_row,
)
from tramflow_ml.features.history import (
    anchor_start,
    available_value,
    carries_unit_ratio,
    lag_features,
    lag_names,
    rolling_features,
    rolling_names,
    seasonal_features,
    seasonal_names,
    unit_counts,
)
from tramflow_ml.features.periods import (
    bucket_dates,
    bucket_from_start,
    bucket_of,
    bucket_start_of,
    granularity_for,
    horizon_buckets,
    service_date,
    step,
)
from tramflow_ml.features.policy import (
    DAY_HOUR,
    MONTH_DAY,
    POLICIES,
    YEAR_MONTH,
    HorizonPolicy,
    policy_by_name,
)
from tramflow_ml.features.records import (
    COUNT_TARGETS,
    COUNT_UNIT,
    FEATURE_VERSION,
    MOSCOW,
    AggregateCell,
    Bucket,
    CapacityRecord,
    Coverage,
    EntityKey,
    FeatureError,
    FeatureHeader,
    FeatureRow,
    FeatureTable,
    FeatureValue,
    Granularity,
    Horizon,
    Observation,
    encode,
    spans_multiple_dates,
    validate_count_pair,
)

__all__ = [
    "COUNT_TARGETS",
    "COUNT_UNIT",
    "DAY_HOUR",
    "ENTITY_CAPACITY",
    "FEATURE_VERSION",
    "HORIZON_INDEX",
    "MONTH_DAY",
    "MOSCOW",
    "POLICIES",
    "YEAR_MONTH",
    "AggregateCell",
    "AggregateIndex",
    "Bucket",
    "CapacityRecord",
    "Coverage",
    "CoverageCalendar",
    "CoverageView",
    "EntityKey",
    "FeatureError",
    "FeatureHeader",
    "FeatureRequest",
    "FeatureRow",
    "FeatureTable",
    "FeatureValue",
    "Granularity",
    "Horizon",
    "HorizonPolicy",
    "Observation",
    "aggregate",
    "anchor_start",
    "available_value",
    "bucket_dates",
    "bucket_from_start",
    "bucket_of",
    "bucket_start_of",
    "build_features",
    "calendar_feature_names",
    "calendar_features",
    "carries_unit_ratio",
    "encode",
    "entity_keys",
    "feature_names",
    "granularity_for",
    "horizon_buckets",
    "lag_features",
    "lag_names",
    "load_entity_keys",
    "load_observations",
    "observation_from_row",
    "policy_by_name",
    "rolling_features",
    "rolling_names",
    "seasonal_features",
    "seasonal_names",
    "service_date",
    "spans_multiple_dates",
    "step",
    "unit_counts",
    "validate_count_pair",
]
