/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/forecasts": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Forecast */
        readonly get: operations["get_forecast_api_v1_forecasts_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/health/live": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Liveness */
        readonly get: operations["liveness_api_v1_health_live_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/health/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Readiness
         * @description Ready means every dependency needed to answer is in place, not just the database.
         *
         *     The graph is loaded here rather than on the first request that needs it, so a
         *     deployment shipped without it reports unready instead of looking healthy and then
         *     failing whichever request happens to arrive first.
         */
        readonly get: operations["readiness_api_v1_health_ready_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/overpass/query": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Run Query */
        readonly post: operations["run_query_api_v1_overpass_query_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/overpass/status": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Status
         * @description Probe the upstream instance.
         *
         *     Always 200: an unreachable Overpass is a fact for the dispatcher UI to display,
         *     not a failure of this API. Readiness of the service itself is `/health/ready`.
         */
        readonly get: operations["get_status_api_v1_overpass_status_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/planning/forecast": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Planning Forecast */
        readonly post: operations["planning_forecast_api_v1_planning_forecast_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/routes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Routes */
        readonly get: operations["list_routes_api_v1_routes_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/routes/{route_id}/stops": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Route Stops */
        readonly get: operations["list_route_stops_api_v1_routes__route_id__stops_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/scenarios/evaluate": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Evaluate Scenario */
        readonly post: operations["evaluate_scenario_api_v1_scenarios_evaluate_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tram-graph/edges": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Edges */
        readonly get: operations["list_edges_api_v1_tram_graph_edges_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tram-graph/geojson": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Geojson
         * @description The network as a GeoJSON FeatureCollection, stops as points and track as lines.
         */
        readonly get: operations["get_geojson_api_v1_tram_graph_geojson_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tram-graph/path": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Find Path
         * @description Cheapest ride between two stops by track distance.
         *
         *     An unreachable pair answers 200 with `found=false` and a `reason`. The network is
         *     genuinely in two disconnected pieces and its edges are directed, so "no such ride"
         *     is information about the city, not a client error.
         */
        readonly get: operations["find_path_api_v1_tram_graph_path_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tram-graph/routes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Routes */
        readonly get: operations["list_routes_api_v1_tram_graph_routes_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tram-graph/routes/{ref}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Route */
        readonly get: operations["get_route_api_v1_tram_graph_routes__ref__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tram-graph/stats": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Stats */
        readonly get: operations["get_stats_api_v1_tram_graph_stats_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tram-graph/stops": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Search Stops */
        readonly get: operations["search_stops_api_v1_tram_graph_stops_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tram-graph/stops/{stop_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Stop */
        readonly get: operations["get_stop_api_v1_tram_graph_stops__stop_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Factor */
        readonly Factor: {
            /**
             * Enabled
             * @default false
             */
            readonly enabled: boolean;
            /**
             * Multiplier
             * @default 1
             */
            readonly multiplier: number;
        };
        /** Factors */
        readonly Factors: {
            readonly calendar?: components["schemas"]["Factor"];
            readonly events?: components["schemas"]["Factor"];
            readonly traffic?: components["schemas"]["Factor"];
            readonly weather?: components["schemas"]["Factor"];
        };
        /**
         * ForecastHorizon
         * @enum {string}
         */
        readonly ForecastHorizon: "day" | "month" | "year";
        /** ForecastMapPositionResponse */
        readonly ForecastMapPositionResponse: {
            /** Direction Id */
            readonly direction_id: string | null;
            /** Latitude */
            readonly latitude: number | null;
            /** Longitude */
            readonly longitude: number | null;
            /** Osm Stop Id */
            readonly osm_stop_id: number | null;
            /**
             * Position Kind
             * @enum {string}
             */
            readonly position_kind: "osm" | "synthetic_demo" | "unavailable";
            /** Reason */
            readonly reason: string;
            /**
             * Status
             * @enum {string}
             */
            readonly status: "matched" | "unmatched" | "ambiguous";
            /** Stop Id */
            readonly stop_id: number;
        };
        /** ForecastMapResponse */
        readonly ForecastMapResponse: {
            /** Ambiguous Count */
            readonly ambiguous_count: number;
            /** Entity Version */
            readonly entity_version: string | null;
            /** Graph Version */
            readonly graph_version: string | null;
            /** Mapping Version */
            readonly mapping_version: string | null;
            /** Matched Count */
            readonly matched_count: number;
            /** Positions */
            readonly positions: readonly components["schemas"]["ForecastMapPositionResponse"][];
            /** Reason */
            readonly reason: string;
            /** Run Id */
            readonly run_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            readonly status: "ready" | "partial" | "unavailable";
            /** Synthetic */
            readonly synthetic: boolean;
            /** Unmatched Count */
            readonly unmatched_count: number;
        };
        /** ForecastPointResponse */
        readonly ForecastPointResponse: {
            /** Capacity */
            readonly capacity: number | null;
            /** Lower Bound */
            readonly lower_bound: number | null;
            /** Predicted Passengers */
            readonly predicted_passengers: number;
            /**
             * Timestamp
             * Format: date-time
             */
            readonly timestamp: string;
            /** Upper Bound */
            readonly upper_bound: number | null;
        };
        /** ForecastResponse */
        readonly ForecastResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            readonly generated_at: string;
            readonly horizon: components["schemas"]["ForecastHorizon"];
            readonly map?: components["schemas"]["ForecastMapResponse"] | null;
            /** Model Version */
            readonly model_version: string;
            /** Peak Load Percent */
            readonly peak_load_percent: number | null;
            /** Peak Passengers */
            readonly peak_passengers: number;
            /** Points */
            readonly points: readonly components["schemas"]["ForecastPointResponse"][];
            readonly route: components["schemas"]["RouteResponse"];
            readonly run?: components["schemas"]["ForecastRunResponse"] | null;
            readonly selection?: components["schemas"]["ForecastSelectionResponse"] | null;
            /** Stop Points */
            readonly stop_points?: readonly components["schemas"]["StopForecastPointResponse"][] | null;
            /** Stops */
            readonly stops: readonly components["schemas"]["StopLoadResponse"][];
        };
        /** ForecastRunResponse */
        readonly ForecastRunResponse: {
            /** Calendar Version */
            readonly calendar_version: string;
            /**
             * Data Cutoff
             * Format: date-time
             */
            readonly data_cutoff: string;
            /** Dataset Id */
            readonly dataset_id: string;
            /** Entity Version */
            readonly entity_version: string;
            /** Feature Version */
            readonly feature_version: string;
            /**
             * Forecast Origin
             * Format: date-time
             */
            readonly forecast_origin: string;
            /** Graph Version */
            readonly graph_version: string | null;
            /** Identity Namespace */
            readonly identity_namespace: string;
            /** Interval Level */
            readonly interval_level: number | null;
            /** Interval Method */
            readonly interval_method: string | null;
            /** Run Id */
            readonly run_id: string;
            /** Source Version */
            readonly source_version: string;
            /** Synthetic */
            readonly synthetic: boolean;
            /** Target */
            readonly target: string;
            /** Unit */
            readonly unit: string;
        };
        /** ForecastSelectionResponse */
        readonly ForecastSelectionResponse: {
            /** Aggregation Key */
            readonly aggregation_key: string;
            /** Direction Id */
            readonly direction_id: string | null;
            /**
             * End
             * Format: date-time
             */
            readonly end: string;
            /** Interval Aggregation */
            readonly interval_aggregation: string;
            /**
             * Start
             * Format: date-time
             */
            readonly start: string;
            /** Stop Id */
            readonly stop_id: number | null;
        };
        /** GeoJsonMetadataResponse */
        readonly GeoJsonMetadataResponse: {
            /** Area */
            readonly area?: string | null;
            /** Filtered To Route */
            readonly filtered_to_route?: string | null;
            /** Generated At */
            readonly generated_at?: string | null;
            /** License */
            readonly license?: string | null;
            /**
             * Missing Geometry Edges
             * @default 0
             */
            readonly missing_geometry_edges: number;
            /** Osm Data Timestamp */
            readonly osm_data_timestamp?: string | null;
            /** Route Relations */
            readonly route_relations?: number | null;
            /** Source */
            readonly source?: string | null;
            /**
             * Synthetic
             * @default false
             */
            readonly synthetic: boolean;
        };
        /**
         * GeometryQuality
         * @enum {string}
         */
        readonly GeometryQuality: "provided" | "inferred" | "synthetic";
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /** LineStringGeometry */
        readonly LineStringGeometry: {
            /** Coordinates */
            readonly coordinates: readonly (readonly [
                number,
                number
            ])[];
            /**
             * Type
             * @default LineString
             * @constant
             */
            readonly type: "LineString";
        };
        /**
         * NeighbourDirection
         * @enum {string}
         */
        readonly NeighbourDirection: "in" | "out";
        /** NetworkComponentResponse */
        readonly NetworkComponentResponse: {
            /** Routes */
            readonly routes: readonly string[];
            /** Size */
            readonly size: number;
        };
        /** NetworkStatsResponse */
        readonly NetworkStatsResponse: {
            /**
             * Components
             * @description Undirected components, largest first; the network really is in two pieces
             */
            readonly components: readonly components["schemas"]["NetworkComponentResponse"][];
            /** Degree Histogram */
            readonly degree_histogram: {
                readonly [key: string]: number;
            };
            /**
             * Edges
             * @description Directed edges; a pair served both ways counts twice
             */
            readonly edges: number;
            /** Generated At */
            readonly generated_at?: string | null;
            /** Osm Data Timestamp */
            readonly osm_data_timestamp?: string | null;
            /**
             * Route Relations
             * @description PTv2 route relations in the OSM extract, one per direction. A larger number than `routes`, and not interchangeable with it.
             */
            readonly route_relations?: number | null;
            /**
             * Routes
             * @description Distinct route refs
             */
            readonly routes: number;
            readonly segment_length_m: components["schemas"]["SegmentLengthSummaryResponse"];
            /** Stops */
            readonly stops: number;
            /** Total Length Km */
            readonly total_length_km: number;
        };
        /** OverpassQueryRequest */
        readonly OverpassQueryRequest: {
            /**
             * Query
             * @description Overpass QL. The length ceiling is a runtime setting, not part of this schema.
             * @example [out:json][timeout:60];node(1);out;
             */
            readonly query: string;
        };
        /** OverpassQueryResponse */
        readonly OverpassQueryResponse: {
            /**
             * Remark
             * @description Set when Overpass answered 200 with a PARTIAL result because the query hit its own [timeout:]. Lifted out of `result` so it cannot be missed; treating such a response as complete is the easiest way to publish wrong numbers.
             */
            readonly remark?: string | null;
            /**
             * Result
             * @description The Overpass JSON document, unmodified
             */
            readonly result: {
                readonly [key: string]: unknown;
            };
        };
        /** OverpassStatusResponse */
        readonly OverpassStatusResponse: {
            /**
             * Detail
             * @description Why the probe failed; null when the instance answered
             */
            readonly detail?: string | null;
            /** Reachable */
            readonly reachable: boolean;
            /** Url */
            readonly url: string;
        };
        /**
         * PathAbsence
         * @description Why no path was returned, in a form a client can branch on.
         * @enum {string}
         */
        readonly PathAbsence: "unknown_stop" | "different_components" | "wrong_direction";
        /** PlanningPoint */
        readonly PlanningPoint: {
            /** Baseline */
            readonly baseline: number;
            /**
             * Basis
             * @enum {string}
             */
            readonly basis: "competition_period" | "scenario_projection";
            /**
             * Bucket End
             * Format: date-time
             */
            readonly bucket_end: string;
            /** Route Baseline */
            readonly route_baseline: number;
            /** Route Scenario */
            readonly route_scenario: number;
            /** Route Unallocated Baseline */
            readonly route_unallocated_baseline: number;
            /** Route Unallocated Scenario */
            readonly route_unallocated_scenario: number;
            /** Scenario */
            readonly scenario: number;
            /** Spatial */
            readonly spatial: readonly components["schemas"]["SpatialPoint"][];
            /**
             * Timestamp
             * Format: date-time
             */
            readonly timestamp: string;
            /** Unallocated Baseline */
            readonly unallocated_baseline: number;
            /** Unallocated Scenario */
            readonly unallocated_scenario: number;
        };
        /** PlanningRequest */
        readonly PlanningRequest: {
            /** Direction */
            readonly direction?: string | null;
            readonly factors?: components["schemas"]["Factors"];
            /**
             * Forecast Mode
             * @default approved
             * @enum {string}
             */
            readonly forecast_mode: "approved" | "external_experiment" | "stop_model";
            /**
             * Horizon
             * @default day
             * @enum {string}
             */
            readonly horizon: "day" | "month" | "year";
            /** Route */
            readonly route: string;
            readonly source_enabled?: components["schemas"]["SourceFlags"];
            /**
             * Start Date
             * Format: date
             */
            readonly start_date: string;
            /** Stop Id */
            readonly stop_id?: string | null;
        };
        /** PlanningResponse */
        readonly PlanningResponse: {
            /** Direction */
            readonly direction?: string | null;
            /** Experimental Evaluation */
            readonly experimental_evaluation: string | null;
            readonly factors?: components["schemas"]["Factors"];
            /**
             * Forecast Mode
             * @default approved
             * @enum {string}
             */
            readonly forecast_mode: "approved" | "external_experiment" | "stop_model";
            /** Generated At */
            readonly generated_at: string;
            /**
             * Horizon
             * @default day
             * @enum {string}
             */
            readonly horizon: "day" | "month" | "year";
            /** Model Version */
            readonly model_version: string;
            /** Points */
            readonly points: readonly components["schemas"]["PlanningPoint"][];
            /** Provenance */
            readonly provenance: {
                readonly [key: string]: string;
            };
            /** Qualitative */
            readonly qualitative: boolean;
            /** Route */
            readonly route: string;
            /** Routes */
            readonly routes: readonly string[];
            /** Run Id */
            readonly run_id: string;
            readonly source_enabled?: components["schemas"]["SourceFlags"];
            /** Sources */
            readonly sources: readonly components["schemas"]["PlanningSource"][];
            /**
             * Start Date
             * Format: date
             */
            readonly start_date: string;
            /** Stop Id */
            readonly stop_id?: string | null;
            /** Stops */
            readonly stops: readonly components["schemas"]["PlanningStop"][];
            /**
             * Timezone
             * @constant
             */
            readonly timezone: "Europe/Moscow";
            /**
             * Unit
             * @constant
             */
            readonly unit: "event_count";
            /** Warnings */
            readonly warnings: readonly string[];
        };
        /** PlanningSource */
        readonly PlanningSource: {
            /** Detail */
            readonly detail: string;
            /** Id */
            readonly id: string;
            /** Label */
            readonly label: string;
            /** Status */
            readonly status: string;
            /** Url */
            readonly url: string | null;
        };
        /** PlanningStop */
        readonly PlanningStop: {
            /** Direction */
            readonly direction: string;
            /** Latitude */
            readonly latitude: number | null;
            /** Longitude */
            readonly longitude: number | null;
            /** Name */
            readonly name: string;
            /** Stop Id */
            readonly stop_id: string;
        };
        /** PointGeometry */
        readonly PointGeometry: {
            /** Coordinates */
            readonly coordinates: readonly [
                number,
                number
            ];
            /**
             * Type
             * @default Point
             * @constant
             */
            readonly type: "Point";
        };
        /** RouteDetailResponse */
        readonly RouteDetailResponse: {
            /** Component */
            readonly component: number;
            /** Edges */
            readonly edges: readonly components["schemas"]["TramEdgeResponse"][];
            /** Length M */
            readonly length_m: number;
            /** Ref */
            readonly ref: string;
            /** Stops */
            readonly stops: readonly components["schemas"]["TramStopResponse"][];
        };
        /** RouteResponse */
        readonly RouteResponse: {
            /** Color */
            readonly color: string;
            /** Id */
            readonly id: number;
            /** Name */
            readonly name: string;
            /** Number */
            readonly number: string;
        };
        /** RouteStopResponse */
        readonly RouteStopResponse: {
            /** Id */
            readonly id: number;
            /** Latitude */
            readonly latitude: number;
            /** Longitude */
            readonly longitude: number;
            /** Name */
            readonly name: string;
            /** Sequence */
            readonly sequence: number;
        };
        /** ScenarioRequest */
        readonly ScenarioRequest: {
            /**
             * Additional Vehicles
             * @default 0
             */
            readonly additional_vehicles: number;
            /**
             * Demand Change Percent
             * @default 0
             */
            readonly demand_change_percent: number;
            /** @default day */
            readonly horizon: components["schemas"]["ForecastHorizon"];
            /**
             * Interval Change Percent
             * @default 0
             */
            readonly interval_change_percent: number;
            /** Route Id */
            readonly route_id: number;
        };
        /** ScenarioResponse */
        readonly ScenarioResponse: {
            /** Affected Stops */
            readonly affected_stops: readonly components["schemas"]["StopLoadResponse"][];
            /** Baseline Peak Load Percent */
            readonly baseline_peak_load_percent: number | null;
            /** Capacity Delta */
            readonly capacity_delta: number;
            /** Passenger Delta */
            readonly passenger_delta: number;
            /** Scenario Peak Load Percent */
            readonly scenario_peak_load_percent: number | null;
            /** Solver Version */
            readonly solver_version: string;
        };
        /** SegmentFeature */
        readonly SegmentFeature: {
            readonly geometry: components["schemas"]["LineStringGeometry"];
            readonly properties: components["schemas"]["SegmentFeatureProperties"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            readonly type: "Feature";
        };
        /** SegmentFeatureProperties */
        readonly SegmentFeatureProperties: {
            readonly geometry_quality: components["schemas"]["GeometryQuality"];
            /** Length M */
            readonly length_m: number;
            /** Routes */
            readonly routes: readonly string[];
            /** Source */
            readonly source: number;
            /** Target */
            readonly target: number;
        };
        /** SegmentLengthSummaryResponse */
        readonly SegmentLengthSummaryResponse: {
            /** Max */
            readonly max: number;
            /** Mean */
            readonly mean: number;
            /** Median */
            readonly median: number;
            /** Min */
            readonly min: number;
        };
        /** SourceFlags */
        readonly SourceFlags: {
            /**
             * Calendar
             * @default false
             */
            readonly calendar: boolean;
            /**
             * Events
             * @default false
             */
            readonly events: boolean;
            /**
             * Traffic
             * @default false
             */
            readonly traffic: boolean;
            /**
             * Weather
             * @default false
             */
            readonly weather: boolean;
        };
        /** SpatialPoint */
        readonly SpatialPoint: {
            /** Baseline */
            readonly baseline: number;
            /** Direction */
            readonly direction: string;
            /** Latitude */
            readonly latitude: number | null;
            /** Longitude */
            readonly longitude: number | null;
            /** Name */
            readonly name: string;
            /** Scenario */
            readonly scenario: number;
            /** Stop Id */
            readonly stop_id: string;
        };
        /** StopDetailResponse */
        readonly StopDetailResponse: {
            /**
             * Id
             * @description OSM stop_position node id
             */
            readonly id: number;
            /** Latitude */
            readonly latitude: number;
            /** Longitude */
            readonly longitude: number;
            /** Name */
            readonly name: string;
            /** Neighbours */
            readonly neighbours: readonly components["schemas"]["StopNeighbourResponse"][];
            /** Routes */
            readonly routes: readonly string[];
        };
        /** StopFeature */
        readonly StopFeature: {
            readonly geometry: components["schemas"]["PointGeometry"];
            readonly properties: components["schemas"]["StopFeatureProperties"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            readonly type: "Feature";
        };
        /** StopFeatureProperties */
        readonly StopFeatureProperties: {
            /** Id */
            readonly id: number;
            /** Name */
            readonly name: string;
            /** Routes */
            readonly routes: readonly string[];
        };
        /** StopForecastPointResponse */
        readonly StopForecastPointResponse: {
            /** Aggregation Scope */
            readonly aggregation_scope: string;
            /** Bucket End */
            readonly bucket_end: string | null;
            /** Capacity */
            readonly capacity: number | null;
            /** Direction Id */
            readonly direction_id: string | null;
            /** Lower Bound */
            readonly lower_bound: number | null;
            /** Predicted Passengers */
            readonly predicted_passengers: number;
            /** Stop Id */
            readonly stop_id: number;
            /**
             * Timestamp
             * Format: date-time
             */
            readonly timestamp: string;
            /** Upper Bound */
            readonly upper_bound: number | null;
        };
        /** StopLoadResponse */
        readonly StopLoadResponse: {
            /** Id */
            readonly id: number;
            /** Latitude */
            readonly latitude: number;
            /** Load Percent */
            readonly load_percent: number | null;
            /** Longitude */
            readonly longitude: number;
            /** Name */
            readonly name: string;
            /** Predicted Passengers */
            readonly predicted_passengers: number;
            /** Sequence */
            readonly sequence: number;
        };
        /** StopNeighbourResponse */
        readonly StopNeighbourResponse: {
            readonly direction: components["schemas"]["NeighbourDirection"];
            /** Id */
            readonly id: number;
            /** Length M */
            readonly length_m: number;
            /** Name */
            readonly name: string;
            /** Routes */
            readonly routes: readonly string[];
        };
        /** TramEdgeResponse */
        readonly TramEdgeResponse: {
            /**
             * Length M
             * @description Metres along the track, not as the crow flies
             */
            readonly length_m: number;
            /** Routes */
            readonly routes: readonly string[];
            /** Source */
            readonly source: number;
            /** Target */
            readonly target: number;
        };
        /**
         * TramGraphGeoJson
         * @description A GeoJSON FeatureCollection: stops as Points, track segments as LineStrings.
         */
        readonly TramGraphGeoJson: {
            /** Features */
            readonly features: readonly (components["schemas"]["StopFeature"] | components["schemas"]["SegmentFeature"])[];
            readonly metadata: components["schemas"]["GeoJsonMetadataResponse"];
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            readonly type: "FeatureCollection";
        };
        /** TramPathResponse */
        readonly TramPathResponse: {
            /** Found */
            readonly found: boolean;
            /**
             * Geometry
             * @description [lon, lat] pairs; inferred paths contain straight endpoint connectors
             */
            readonly geometry: readonly (readonly [
                number,
                number
            ])[];
            readonly geometry_quality?: components["schemas"]["GeometryQuality"] | null;
            /**
             * Missing Geometry Edges
             * @default 0
             */
            readonly missing_geometry_edges: number;
            /**
             * Reason
             * @description The same cause in English prose, for a human reading the API directly.
             */
            readonly reason?: string | null;
            /** @description Why there is no such ride, as a value a client can branch on. Present with `found=false`, which is a 200. Prefer this over `reason` for anything the user sees: `reason` is English prose. */
            readonly reason_code?: components["schemas"]["PathAbsence"] | null;
            /** Routes */
            readonly routes: readonly string[];
            /** Stops */
            readonly stops: readonly components["schemas"]["TramStopResponse"][];
            /** Total Length M */
            readonly total_length_m: number;
        };
        /** TramRouteResponse */
        readonly TramRouteResponse: {
            /**
             * Component
             * @description 0 is the main network, 1 the northern one
             */
            readonly component: number;
            /** Length M */
            readonly length_m: number;
            /**
             * Ref
             * @description Route ref as OSM carries it; not always numeric ("А", "т1")
             */
            readonly ref: string;
            /** Stop Count */
            readonly stop_count: number;
        };
        /**
         * TramStopResponse
         * @description `latitude`/`longitude`, matching the forecast slice's StopResponse.
         *
         *     The committed graph files call these `lat`/`lon`; that spelling stops at the
         *     repository, so one API does not expose two names for one concept. Original
         *     docstring follows.
         *
         *     These are the field names in
         *     `docs/tram-graph.md`, the committed GeoJSON and every map library.
         */
        readonly TramStopResponse: {
            /**
             * Id
             * @description OSM stop_position node id
             */
            readonly id: number;
            /** Latitude */
            readonly latitude: number;
            /** Longitude */
            readonly longitude: number;
            /** Name */
            readonly name: string;
            /** Routes */
            readonly routes: readonly string[];
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Context */
            readonly ctx?: Record<string, never>;
            /** Input */
            readonly input?: unknown;
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly get_forecast_api_v1_forecasts_get: {
        readonly parameters: {
            readonly query: {
                readonly direction_id?: string | null;
                readonly end?: string | null;
                readonly horizon?: components["schemas"]["ForecastHorizon"];
                readonly route_id: number;
                readonly start?: string | null;
                readonly stop_id?: number | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly liveness_api_v1_health_live_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly readiness_api_v1_health_ready_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly run_query_api_v1_overpass_query_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["OverpassQueryRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OverpassQueryResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_status_api_v1_overpass_status_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OverpassStatusResponse"];
                };
            };
        };
    };
    readonly planning_forecast_api_v1_planning_forecast_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PlanningRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PlanningResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_routes_api_v1_routes_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["RouteResponse"][];
                };
            };
        };
    };
    readonly list_route_stops_api_v1_routes__route_id__stops_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly route_id: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["RouteStopResponse"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly evaluate_scenario_api_v1_scenarios_evaluate_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_edges_api_v1_tram_graph_edges_get: {
        readonly parameters: {
            readonly query?: {
                /** @description Restrict to one route ref */
                readonly route?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["TramEdgeResponse"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_geojson_api_v1_tram_graph_geojson_get: {
        readonly parameters: {
            readonly query?: {
                /** @description Restrict to one route ref */
                readonly route?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TramGraphGeoJson"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly find_path_api_v1_tram_graph_path_get: {
        readonly parameters: {
            readonly query: {
                /** @description Source stop id */
                readonly from: number;
                /** @description Target stop id */
                readonly to: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TramPathResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_routes_api_v1_tram_graph_routes_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["TramRouteResponse"][];
                };
            };
        };
    };
    readonly get_route_api_v1_tram_graph_routes__ref__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly ref: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RouteDetailResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_stats_api_v1_tram_graph_stats_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["NetworkStatsResponse"];
                };
            };
        };
    };
    readonly search_stops_api_v1_tram_graph_stops_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
                /** @description Case-insensitive substring of the stop name */
                readonly q?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["TramStopResponse"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_stop_api_v1_tram_graph_stops__stop_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly stop_id: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StopDetailResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
